### ISSUE TITLE
Polishing the repo

### ISSUE THREAD

**Issue by rgolangh** [parodos-dev/serverless-workflows-helm#41]
- Add values.schema.json for main chart and for each of the workflows
- Add icon
- Add CONTRIBUTION.md to list requirements for any new workflow (also add a reference to https://github.com/parodos-dev/serverless-workflows) to be familiar with the process to update the CR

**Comment by rgolangh** [comment]
wan't this auto closed by the PR?

**Comment by masayag** [comment]
It should have been closed by @gabriel-farache first PR. 
I'm polishing the polished PR https://github.com/parodos-dev/serverless-workflows-helm/pull/42

**Comment by gabriel-farache** [comment]
![8eq5kl](https://github.com/parodos-dev/serverless-workflows-helm/assets/3036508/149400ff-d9ec-454d-a116-ddc3267bfe11)
